mailbadger/app

- dashboard/package.json
- entities/campaign.go
- storage/campaign_test.go
- storage/migrations/mysql/1_init.sql
- storage/migrations/sqlite3/1_init.sql
> feat: added deleted_at column for campaigns, implemented soft delete

- dashboard/src/Campaigns/Create.js
- dashboard/src/Campaigns/List.js
- dashboard/src/Subscribers/Create.js
- dashboard/src/Subscribers/Delete.js
- dashboard/src/Subscribers/List.js
- dashboard/src/Templates/List.js
- entities/campaign.go
> feat: create campaign initial implementation done

- actions/subscribers.go
- dashboard/src/Subscribers/Edit.js
- dashboard/src/Subscribers/List.js
- entities/subscriber.go
- storage/subscriber.go
- storage/subscriber_test.go
> feat: edit subscriber

- actions/campaigns.go
- entities/bounce.go
- routes/routes.go
- storage/campaign.go
- storage/campaign_test.go
- storage/storage.go
Implemented Get Campaign bounces by campaign id
Fixes #775 
> Campaign bounces stats

- actions/templates.go
- entities/params/posttemplate.go
- entities/params/puttemplate.go
- validator/validationerror.go
Template actions user input validation
Fixes #522 
> Templates action validate user input 

- actions/s3.go
- entities/params/s3.go
Add s3 actions user input vaalidation
> s3 actions validations

- actions/subscribers.go
- entities/params/subscribers.go
- entities/subscriber.go
- storage/subscriber.go
- storage/subscriber_test.go
- validator/validationerror.go
- validator/validator.go
Validate user input in subscribers endpoints
> subscribers endpoints user input validation

- entities/segment.go
- entities/ses.go
- mailbadger.go
- storage/segment_test.go
- validator/validator.go
> Cleanup old validation

- docker-compose.yaml
- entities/report.go
- go.mod
- go.sum
- storage/migrations/mysql/3_reports.sql
- storage/migrations/sqlite3/3_reports.sql
- storage/report_test.go
- storage/reports.go
- storage/storage.go
> reports migration

- actions/subscribers.go
- routes/routes.go
Download export action implemented
Fixes #541 
> Download export action

- actions/users_test.go
> Add change password tests

- actions/segments_test.go
> segment actions tests

- actions/subscribers.go
- actions/subscribers_test.go
- go.sum
- storage/pagination.go
- storage/storage.go
- storage/subscriber.go
- storage/subscriber_test.go
> Get Subscribers  collection filter,Tests for subscribers actions

- actions/campaigns.go
- actions/templates.go
- actions/templates_test.go
- consumers/campaigner/main.go
- entities/campaign.go
- entities/template.go
- go.sum
- storage/campaign.go
- storage/templates.go
- storage/templates_test.go
> Chore campain template

- consumers/campaigner/main.go
- entities/campaign.go
- services/campaigns/campaigns.go
- services/templates/service.go
> Refactor campaigner consumer

- consumers/campaigner/main.go
- consumers/sender/main.go
- entities/sendlog.go
- entities/template.go
- services/campaigns/campaigns.go
- storage/sendlog_test.go
> Refactor sender

- scripts/run-campaigner.sh
- scripts/run-mailbadger.sh
- scripts/run-sender.sh
- services/campaigns/campaigns.go
> Fix scripts

- actions/hooks.go
- consumers/sender/main.go
- go.sum
> Sender refactor

- services/boundaries/boundaries.go
- storage/campaign.go
- storage/storage.go
> fix: campaigns limit is checked against monthly created campaigns count

- consumers/bulksender/main.go
- consumers/campaigner/main.go
- consumers/sender/main.go
- entities/campaign.go
- entities/sendlog.go
- go.mod
- go.sum
- services/campaigns/campaigns.go
- storage/db.go
- storage/migrations/mysql/1_init.sql
- storage/migrations/mysql/5_message_id_sent_logs.sql
- storage/migrations/mysql/6_ksuid_in_send_logs.sql
- storage/migrations/sqlite3/1_init.sql
- storage/sendlog.go
- storage/sendlog_test.go
- storage/storage.go
> Send log ksuid

- actions/subscribers.go
- services/boundaries/boundaries.go
- services/subscribers/importer/importer.go
- utils/csv.go
> Subscribers Limit

- consumers/sender/main.go
- go.sum
- storage/migrations/mysql/1_init.sql
> Sender improvements

- actions/segments.go
- go.sum
- routes/routes.go
> Ssegments api fixes

- routes/routes.go
- storage/migrations/sqlite3/1_init.sql
- storage/migrations/sqlite3/2_tokens.sql
- storage/migrations/sqlite3/3_reports.sql
- storage/migrations/sqlite3/4_campaign_schedules.sql
- storage/migrations/sqlite3/6_campaign_logs.sql
> Issue 1155/chore sqlite migrations

- storage/migrations/mysql/1_init.sql
- storage/migrations/mysql/2_tokens.sql
- storage/migrations/mysql/3_reports.sql
- storage/migrations/mysql/4_campaign_logs.sql
- storage/migrations/mysql/5_campaign_schedules.sql
- storage/migrations/sqlite3/1_init.sql
- storage/migrations/sqlite3/2_tokens.sql
- storage/migrations/sqlite3/3_reports.sql
- storage/migrations/sqlite3/4_campaign_schedules.sql
- storage/migrations/sqlite3/6_campaign_logs.sql
> Formated and sync all migrations

- go.sum
- services/templates/service.go
> Add template bucket in the service not as a global variable

- services/templates/service.go
> Improve template path on s3

- actions/campaigns.go
- storage/campaignschedules.go
- storage/campaignschedules_test.go
> Scheduled campaign status

- storage/campaignschedules.go
> Update and delete the event id along with the campaign status

- dashboard/src/App.js
- dashboard/src/Auth/AuthSidebar.js
- dashboard/src/Auth/AuthWrapper.js
- dashboard/src/Auth/ForgotPassword.js
- dashboard/src/Auth/Login.js
- dashboard/src/Dashboard.js
- dashboard/src/Sidebar.js
- dashboard/src/Subscribers/List.js
- dashboard/src/Subscribers/StyledSections.js
- dashboard/src/Subscribers/index.js
- dashboard/src/ui/Auth/AuthFormFieldError.js
- dashboard/src/ui/Checkbox.js
- dashboard/src/ui/DashboardDataTable.js
- dashboard/src/ui/DashboardPlaceholderTable.js
- dashboard/src/ui/DashboardStyledTable.js
- dashboard/src/ui/PlaceholderRow.js
- dashboard/src/ui/StyledTable.js
-Styling for dashboard data table which will be a re-usable component implemented later on all dashboard pages where a table is required. 
-Fix for the respective placeholder table
-Implemented  local table search which will filter data per page
-Fixed styling for actions buttons above table 
> 1266: Dashboard table & actions buttons styling

- .prettierrc
- .vscode/settings.json
- dashboard/package.json
Added prettier config and vscode settings.
Fixes #1570 
> Added prettier config and vscode prettier settings for default formatter
